### ISSUE TITLE
startDate and endDate for seeding challenges

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/rocc-service#89]
The `startDate` and `endDate` are both required for creating challenge request now. The `startDate` and `endDate` only accept `date` type, and not accept `""`, which makes sense. 

https://github.com/Sage-Bionetworks/rocc/blob/ae3f760e1c464f3c95dee4cf08336d6016ef6a5b/server/openapi_server/models/challenge_create_request.py#L42-L43

However, it may not fit for all circumstances. For example:
- For current running challenges, they may not specify end dates 
- For upcoming challenges, they may not have either start dates or end dates

- [ ] We will make dates to optional in [schema](https://github.com/Sage-Bionetworks/rocc-schemas/blob/develop/openapi/components/schemas/ChallengeCreateRequest.yaml) for now.

**Comment by tschaffter** [comment]
Start and end date are option properties since #103

**Comment by tschaffter** [comment]
Done when updating to schemas 0.1.5
